language: php
sudo: false
php:
  - 7.0
  - 5.6
install:
  - composer self-update
  - composer install
  - curl -LSs https://box-project.github.io/box2/installer.php | php
script:
  - php box.phar build
